language: php
script: 
    - phpunit --coverage-clover=coverage.clover
    - rm -rf /tmp/activemongo2
    - export NAMESPACE=root
    - phpunit --coverage-clover=coverage.clover

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
